### p73 선형 회귀 모델
- 데이터를 선형 함수로 모델링
- 최소제곱법 : 평균제곱오차를 최소화하는 파라미터를 찾는다.
    - 파라미터를 줄이고 키우고를 반복한다. (예시)
    - 오차를 파라미터로 미분한 값만큼 조깅을 반복한다.(경사하강법)
    - 정규방정식으로 찾기 (데이터가 많아지면 메모리 부족으로 사용 불가)
- 평균제곱오차 : 오차(예측과 정답의 차이)를 제곱 > 모든 샘플들의 오차를 평균

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [12]:
#키와 몸부게, 몸무게로부터 키를 예측해보자
몸무게 = [30,60,70,90]
키 = [120,160,170,190]
몸무게_test = [65, 80]  # 이 두사람의 키는 어떻게 될까?

In [13]:
몸무게 = np.array(몸무게).reshape((-1,1))
키 = np.array(키)
몸무게_test = np.array(몸무게_test).reshape((-1,1))

In [14]:
#76 모델 선택
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X=몸무게, y=키)  # Y=w*x+b 에서 w와 b를 조절하는 것

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [15]:
몸무게_test, lr.predict(몸무게_test)

(array([[65],
        [80]]), array([162.93333333, 180.53333333]))

In [16]:
몸무게

array([[30],
       [60],
       [70],
       [90]])

In [18]:
lr.score(몸무게,키) # 결정계수 max 1

0.9928205128205129

In [19]:
#계수 w와 절편 b
lr.coef_, lr.intercept_

(array([1.17333333]), 86.66666666666667)

In [20]:
lr.coef_ * 몸무게 + lr.intercept_

array([[121.86666667],
       [157.06666667],
       [168.8       ],
       [192.26666667]])

In [21]:
키

array([120, 160, 170, 190])